import type { NextPage } from 'next'
import Head from 'next/head';
import Header from '../components/header/header';
import MainOne from '../components/main-one/main_one';
import MainTwo from '../components/main-one/main_two';


export const layoutStyle = {
    marginLeft: '12%',
    marginRight: '12%',
}
const Version2: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Fyatu.com</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='mb-16'>
                <div style={layoutStyle}>
                    <Header />
                    <section>
                        <MainTwo />
                    </section>
                </div>
            </div>
            <section className=' h-56 w-full bg-sky-900'>
                <p></p>
            </section>
        </div>
    );
}

export default Version2;